### ISSUE TITLE
[suggestion] Optimize of Event Trigged Query

### ISSUE THREAD

**Issue by betayi** [febaut/mod-tabard-utilities#1]
OnCreatureKilled is a function called very frequently, an SQL excution included in it repeat oftenly will make a lot of cost and wait to get the result without modified , load the custom records from database on load procedure is a nice solution

**Comment by febaut** [comment]
Thank you for your suggestion. I've managed to improve the script. Check the source again ^^

**Comment by betayi** [comment]
nice job!
